writeEnvVars: ${{self:custom.current.environment}}

default:
  stage: local
  region: ap-southeast-2

stages:
  local:
    profile: asynchronous
    memorySize: 128
    timeout: 30
    environment:
      APPLICATION_NAME: Asynchronous
      APPLICATION_VERSION: 0.0.1
      ENVIRONMENT_NAME: local
      ENVIRONMENT_TYPE: local

current:
  stage: ${{opt:stage, self:custom.default.stage}}
  region: ${{opt:region, self:custom.stages.${{self:custom.current.stage}}.region, self:custom.default.region}}
  memorySize: ${{opt:memorySize, self:custom.stages.${{self:custom.current.stage}}.memorySize, self:custom.default.memorySize}}
  timeout: ${{opt:timeout, self:custom.stages.${{self:custom.current.stage}}.timeout, self:custom.default.timeout}}
  environment: ${{self:custom.stages.${{self:custom.current.stage}}.environment, self:custom.default.environment}}
